### PR TITLE
Added: Track searching

### PR DESCRIPTION
**Pull request by danielunderwood**
* Adds the capability to search for track under `/search/track` and `/search?type=track`
* Increases the fuzziness and performance of artist and album searches
* Fixes an issue with album searches obeying the artist parameter

### CODE REVIEW

**Comment by Qstick** [comment]
Do we want to add the artist alias and sortname bit to this PR as well or have that separate?

**Comment by danielunderwood** [comment]
I'll go ahead and add those changes in this PR since we're doing a fair bit of search testing at the moment.

**Comment by Qstick** [comment]
Should we bump 0.4 on this so that beta build doesn't pick it up and start adding various artist and other such blacklisted artists?

**Comment by danielunderwood** [comment]
Merged manually by bd6d956.

**Pull request closed without merging**
